- hosts: all
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: install tools via apt
      apt:
        name:
          - git
          - zsh
          - megatools
          - duplicity
          - openjdk-16-jdk
          - xrdp
          - jq
